baseURL = 'https://tsuna-can.github.io/playground-hugo/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'Playground for Hugo'
theme = 'PaperMod'

[params]
  text_color = 'dark-gray'
  background_color_class = 'bg-navy'
  author = 'Tsunacan'
  favicon = '/images/profile.png'
  site_logo = '/images/profile.png'
  disableSpecial1stPost = true